name: Generate Documentation PDFs
on:
  push:
    paths:
      - 'lab1/README.md'
      - 'lab1/batch_runs/README.md'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    name: Generate Documentation PDFs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-latex-extra
          
      - name: Create PDF directories
        run: |
          mkdir -p lab1/pdf
          mkdir -p lab1/batch_runs/pdf
          
      - name: Generate main README PDF
        run: |
          pandoc lab1/README.md \
            --from markdown \
            --template=https://raw.githubusercontent.com/openjournals/joss/master/assets/latex.template \
            --pdf-engine=xelatex \
            -o lab1/pdf/README.pdf
        
      - name: Generate batch runs README PDF
        if: hashFiles('lab1/batch_runs/README.md') != ''
        run: |
          pandoc lab1/batch_runs/README.md \
            --from markdown \
            --template=https://raw.githubusercontent.com/openjournals/joss/master/assets/latex.template \
            --pdf-engine=xelatex \
            -o lab1/batch_runs/pdf/README.pdf
            
      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: documentation-pdfs
          path: |
            lab1/pdf/README.pdf
            lab1/batch_runs/pdf/README.pdf
          retention-days: 90